---
ntp_timezone: Europe/Dublin

firewall_allowed_tcp_ports:
  - "22"
  - "8080"

jenkins_package_state: latest
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_plugins: [
	'ansible', 
	'git', 
	'github', 
        'pipeline-build-step',
        'pipeline-graph-analysis',
        'pipeline-input-step',
        'pipeline-maven',
        'pipeline-milestone-step',
        'pipeline-model-api',
        'pipeline-model-declarative-agent',
        'pipeline-model-definition',
        'pipeline-model-extensions',
        'pipeline-rest-api',
        'pipeline-stage-step',
        'pipeline-stage-tags-metadata',
        'pipeline-stage-view',
	'pipeline-utility-steps',
        'python-jenkins',
	'disk-usage',
        'workflow-aggregator',
        'workflow-api',
        'workflow-basic-steps',
        'workflow-cps-global-lib',
        'workflow-cps',
        'workflow-durable-task-step',
        'workflow-job',
        'workflow-multibranch',
        'workflow-scm-step',
        'workflow-step-api',
        'workflow-support',
	'ws-cleanup'
]

maven_major: 3
maven_version: 3.5.4
maven_home_parent_directory: /opt

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_service_state: started
docker_service_enabled: yes
docker_restart_handler_state: restarted
docker_install_compose: True
#docker_compose_version: "1.21.2"
docker_compose_path: /usr/local/bin/docker-compose

