---
- hosts: jenkins
  gather_facts: yes
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
    - tecris.maven
    - geerlingguy.ansible
    - geerlingguy.pip
    - geerlingguy.docker
    - docker-setup
    - jenkins-setup

- hosts: app
  gather_facts: yes
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.pip
    - geerlingguy.docker
    - docker-setup
